
def getConversionDict():
    conversion_dict = dict()

    # http://www.kreativekorp.com/charset/unicode.php?block=0300
    cdm_idx_start = '\u0300'
    cdm_idx_end = '\u036F'
    # from \u0300 (768) to \u036F (879)
    for i in range( ord(cdm_idx_start), ord(cdm_idx_end)+1 ):
        conversion_dict[i] = '|'

    # conversion_dict is a hand-curated dictionary of ascii equivalents for common unicode characters in the TCP

    conversion_dict['Œ'] = 'OE'
    conversion_dict['œ'] = 'oe'
    conversion_dict['À'] = 'A'
    conversion_dict['Á'] = 'A'
    conversion_dict['Â'] = 'A'
    conversion_dict['Ã'] = 'A'
    conversion_dict['Ä'] = 'A'
    conversion_dict['Å'] = 'A'
    conversion_dict['Æ'] = 'AE'
    conversion_dict['Ç'] = 'C'
    conversion_dict['È'] = 'E'
    conversion_dict['É'] = 'E'
    conversion_dict['Ê'] = 'E'
    conversion_dict['Ë'] = 'E'
    conversion_dict['Ì'] = 'I'
    conversion_dict['Í'] = 'I'
    conversion_dict['Î'] = 'I'
    conversion_dict['Ï'] = 'I'
    conversion_dict['Ð'] = 'TH'
    conversion_dict['Ñ'] = 'N'
    conversion_dict['Ò'] = 'O'
    conversion_dict['Ó'] = 'O'
    conversion_dict['Ô'] = 'O'
    conversion_dict['Õ'] = 'O'
    conversion_dict['Ö'] = 'O'
    conversion_dict['Ø'] = 'O'
    conversion_dict['Ù'] = 'U'
    conversion_dict['Ú'] = 'U'
    conversion_dict['Û'] = 'U'
    conversion_dict['Ü'] = 'U'
    conversion_dict['Ý'] = 'Y'
    conversion_dict['Þ'] = 'TH'
    conversion_dict['ß'] = 'S'
    conversion_dict['à'] = 'a'
    conversion_dict['á'] = 'a'
    conversion_dict['â'] = 'a'
    conversion_dict['ã'] = 'a'
    conversion_dict['ä'] = 'a'
    conversion_dict['å'] = 'a'
    conversion_dict['æ'] = 'ae'
    conversion_dict['ç'] = 'c'
    conversion_dict['è'] = 'e'
    conversion_dict['é'] = 'e'
    conversion_dict['ê'] = 'e'
    conversion_dict['ë'] = 'e'
    conversion_dict['ē'] = 'e'
    conversion_dict['ì'] = 'i'
    conversion_dict['í'] = 'i'
    conversion_dict['î'] = 'i'
    conversion_dict['ï'] = 'i'
    conversion_dict['ð'] = 'th'
    conversion_dict['ñ'] = 'n'
    conversion_dict['ò'] = 'o'
    conversion_dict['ó'] = 'o'
    conversion_dict['ô'] = 'o'
    conversion_dict['õ'] = 'o'
    conversion_dict['ô'] = 'o'
    conversion_dict['ö'] = 'o'
    conversion_dict['ø'] = 'o'
    conversion_dict['ù'] = 'u'
    conversion_dict['ú'] = 'u'
    conversion_dict['û'] = 'u'
    conversion_dict['ü'] = 'u'
    conversion_dict['ý'] = 'y'
    conversion_dict['þ'] = 'th'
    conversion_dict['ÿ'] = 'y'
    conversion_dict['÷'] = '/'
    conversion_dict['×'] = 'x'
    conversion_dict['¢'] = 'c'
    conversion_dict['£'] = 'L'
    conversion_dict['±'] = '+/-'
    conversion_dict['Ÿ'] = 'Y'
    conversion_dict['š'] = 's'
    conversion_dict['ž'] = 'z'
    ## Latin
    conversion_dict['Ʋ'] = 'V'
    conversion_dict['ʋ'] = 'v'
    ## Greek letters
    conversion_dict['α'] = 'a'
    conversion_dict['β'] = 'b'
    conversion_dict['Γ'] = 'G'
    conversion_dict['γ'] = 'g'
    conversion_dict['Δ'] = 'D'
    conversion_dict['δ'] = 'd'
    conversion_dict['ε'] = 'e'
    conversion_dict['ζ'] = 'z'
    conversion_dict['η'] = 'e'
    conversion_dict['Θ'] = 'TH'
    conversion_dict['θ'] = 'th'
    conversion_dict['η'] = 'e'
    conversion_dict['ι'] = 'i'
    conversion_dict['κ'] = 'k'
    conversion_dict['Λ'] = 'L'
    conversion_dict['λ'] = 'l'
    conversion_dict['μ'] = 'm'
    conversion_dict['ν'] = 'n'
    conversion_dict['Ξ'] = 'X'
    conversion_dict['ξ'] = 'x'
    conversion_dict['Π'] = 'P'
    conversion_dict['π'] = 'p'
    conversion_dict['Λ'] = 'L'
    conversion_dict['ρ'] = 'r'
    conversion_dict['Σ'] = 'S'
    conversion_dict['σ'] = 's'
    conversion_dict['τ'] = 't'
    conversion_dict['υ'] = 'u'
    conversion_dict['Φ'] = 'PH'
    conversion_dict['φ'] = 'ph'
    conversion_dict['χ'] = 'ch'
    conversion_dict['Ψ'] = 'PS'
    conversion_dict['ψ'] = 'ps'
    conversion_dict['Ω'] = 'O'
    conversion_dict['ω'] = 'o'

    # macrons
    conversion_dict['Ā'] = 'A^'
    conversion_dict['Ē'] = 'E^'
    conversion_dict['Ī'] = 'I^'
    conversion_dict['Ō'] = 'O^'
    conversion_dict['Ū'] = 'U^'
    conversion_dict['Ȳ'] = 'Y^'
    conversion_dict['ā'] = 'a^'
    conversion_dict['e'] = 'e^'
    conversion_dict['ī'] = 'i^'
    conversion_dict['ō'] = 'o^'
    conversion_dict['ū'] = 'u^'
    conversion_dict['ȳ'] = 'y^'

    # line breaker
    # http://www.kreativekorp.com/charset/whatis.php
    conversion_dict['∣'] = '|' # unicode 2223 DIVIDES // Deidre: TCP end-of-line straddling soft hyphen
    conversion_dict['▪'] = '*' # unicode 25AA BLACK SMALL SQUARE // Deidre: TCP ambiguious punctuation mark, changed character insertion from | to *
    conversion_dict['¦'] = '|' # unicode 00A6 BROKEN BAR // Deidre: TCP editor inserted end-of-line straddling soft hyphen
    conversion_dict['|'] = '|' # unicode 007C VERTICAL LINE, *EQUAL* to the ascii one
    conversion_dict['❘'] = '|' # unicode 2758 LIGHT VERTICAL BAR
    conversion_dict['ǀ'] = '|' # unicode 01C0 LATIN LETTER DENTAL CLICK
    conversion_dict['∥'] = '|' # unicode 2225 PARALLEL TO

    # special punctuation
    conversion_dict['—'] = '--'
    # no matched
    conversion_dict['¶'] = '|' # Deidre: changed character from * to | so it can be stripped out of text


    #char cleaner expansion


    #punctuation fixes
    conversion_dict['’'] = "'"  #apostrophe fix
    conversion_dict['‐'] = '-'
    conversion_dict['\u2026'] = '...'
    conversion_dict['.'] = '.'
    conversion_dict[' '] = ' '
    conversion_dict['●'] = '^'
    conversion_dict['\xb7'] = '^'
    conversion_dict['\u25CF'] = '^'
    conversion_dict['¯'] = '@'
    conversion_dict['\u2020'] = '@' #dagger
    conversion_dict['\u2021'] = '@' #double dagger
    conversion_dict[u"'"] = '\''
    conversion_dict['\u3009'] = ')'
    conversion_dict['\u3008'] = '('
    conversion_dict['\u25ca'] = '@'
    conversion_dict['\u2011'] = '-'
    conversion_dict['\u201e'] = '"'
    conversion_dict['\xa0'] = ' ' #non-breaking space
    conversion_dict['\u201c'] = '"'
    conversion_dict['\u2022'] = '^'
    conversion_dict['\u2018'] = '\''
    conversion_dict['﻿'] = '@'


    #weird "latin" character conversion
    conversion_dict[u'A'] = 'A'
    conversion_dict[u'B'] = 'B'
    conversion_dict[u'C'] = 'C'
    conversion_dict[u'D'] = 'D'
    conversion_dict[u'E'] = 'E'
    conversion_dict[u'F'] = 'F'
    conversion_dict[u'G'] = 'G'
    conversion_dict[u'H'] = 'H'
    conversion_dict[u'I'] = 'I'
    conversion_dict[u'J'] = 'J'
    conversion_dict[u'K'] = 'K'
    conversion_dict[u'L'] = 'L'
    conversion_dict[u'M'] = 'M'
    conversion_dict[u'N'] = 'N'
    conversion_dict[u'O'] = 'O'
    conversion_dict[u'P'] = 'P'
    conversion_dict[u'Q'] = 'Q'
    conversion_dict[u'R'] = 'R'
    conversion_dict[u'S'] = 'S'
    conversion_dict[u'T'] = 'T'
    conversion_dict[u'U'] = 'U'
    conversion_dict[u'V'] = 'V'
    conversion_dict[u'W'] = 'W'
    conversion_dict[u'X'] = 'X'
    conversion_dict[u'Y'] = 'Y'
    conversion_dict[u'Z'] = 'Z'

    conversion_dict[u'a'] = 'a'
    conversion_dict[u'b'] = 'b'
    conversion_dict[u'c'] = 'c'
    conversion_dict[u'd'] = 'd'
    conversion_dict[u'e'] = 'e'
    conversion_dict[u'f'] = 'f'
    conversion_dict[u'g'] = 'g'
    conversion_dict[u'h'] = 'h'
    conversion_dict[u'i'] = 'i'
    conversion_dict[u'j'] = 'j'
    conversion_dict[u'k'] = 'k'
    conversion_dict[u'l'] = 'l'
    conversion_dict[u'm'] = 'm'
    conversion_dict[u'n'] = 'n'
    conversion_dict[u'o'] = 'o'
    conversion_dict[u'p'] = 'p'
    conversion_dict[u'q'] = 'q'
    conversion_dict[u'r'] = 'r'
    conversion_dict[u's'] = 's'
    conversion_dict[u't'] = 't'
    conversion_dict[u'U'] = 'u'
    conversion_dict[u'v'] = 'v'
    conversion_dict[u'w'] = 'w'
    conversion_dict[u'x'] = 'x'
    conversion_dict[u'y'] = 'y'
    conversion_dict[u'z'] = 'z'


    conversion_dict['\u0163'] = 't'
    conversion_dict['\u014d'] = 'o'
    conversion_dict['\u016b'] = 'u'
    conversion_dict['\u0107'] = 'c'
    conversion_dict['\u01f5'] = 'g'
    conversion_dict['\u017f']= 's'
    conversion_dict['\u0101'] = 'a'
    conversion_dict['\u0391'] = 'A'
    conversion_dict['\u0395'] = 'E'
    conversion_dict['\u0399'] = 'I'
    conversion_dict['\u039d'] = 'N'
    conversion_dict['ă'] = 'a'
    conversion_dict['Ă'] = 'A'
    conversion_dict['Ο'] = 'O'
    conversion_dict['ο'] = 'o'
    conversion_dict['Ρ'] = 'P'
    conversion_dict['Τ'] = 'T'
    conversion_dict['ŭ'] = 'u'
    conversion_dict['ŏ'] = 'o'
    conversion_dict['\u03a5'] = 'Y'

    return conversion_dict